version: '3.7'

services:
  nhp-server:
    build:
      context: .
      target: nhp-server
    image: nhp-server
    privileged: true
    volumes:
      - ./release/nhp-server/etc:/app/etc
    networks:
      - nhpnet

  nhp-agent:
    build:
      context: .
      target: nhp-agent
    image: nhp-agent
    privileged: true
    volumes:
      - ./release/nhp-agent/etc:/app/etc
    networks:
      - nhpnet

  nhp-de:
    build:
      context: .
      target: nhp-db
    image: nhp-de
    privileged: true
    volumes:
      - ./release/nhp-de/etc:/app/etc
    networks:
      - nhpnet

networks:
  nhpnet:
    driver: bridge
